name: emulator

on: workflow_dispatch
    
permissions:
  contents: read
jobs:
  build:
    name: emulator

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v2
        with:
            repository: 1320014053/solana-re
            ref: knn
            path: solana-re
            token: ${{ secrets.MY_TOKEN }}


      - name: build
        run: |
            dir
            cd solana-re
            dir
            vcpkg install openssl:x64-windows-static-md
            cargo update
            cargo build --bin level6

      - name: Copy
        uses: actions/upload-artifact@v3
        with:
            name: release
            path: solana-re/target/debug/level6.exe
